### ISSUE TITLE
راهنمای استفاده از پلاگین

### ISSUE THREAD

**Issue by AMZeitoon** [miladesign/cordova-plugin-adad#1]
خیلی خوب میشه اگه راهنمای استفاده از پلاگین رو هم منتشر کنید.
من پلاگین رو به پروژه اضافه گردم، و توکنی که از سایت عدد گرفتم رو هم درش قرار دادم؛ اما هیچ تغییری نکرد و تبلیغ رو نشون نداد.
ممنون میشم اگر راهنمایی کنید

**Comment by miladesign** [comment]
با سلام
راهنما قرار داده شد
